version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/Ruenzuo/nisekoi
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...